### ISSUE TITLE
Models not successfully updated using Postman. (Read all comments.)

### ISSUE THREAD

**Issue by Panoplos** [mphasize/sails-ember-blueprints#16]
I am just getting into Sails.js with Ember.js as frontend framework and I am using this tool for Sails-side adaptation to Ember request/response protocol. One problem I am running into is when I use Postman to `update` a `user` model with a POST to `http://localhost:1337/users/update/54dd9b22ffe2e5211c1ca77d` and the following values:

```
username: foo
firstName: bar
lastName: baz
```

The user model is failing to be updated. (Note, I have `pluralize` enabled.)

I have added a little debug code to `api/blueprints/update.js` in the following:

```
  // DEBUG >>
  var log = req._sails.log;
  log.debug(
    util.format('/<model>/update called with req.query[%s]\n', JSON.stringify(req.query)) +
    util.format('                                  req.params[%s]',  JSON.stringify(req.params))
  );
  // <<
```

Which outputs:

```
debug: /<model>/update called with req.query[{}]
                                  req.params[[]]
```

As you can see, there is no `params` data being passed to the `Model.update(...)` routine.

Your help will be greatly appreciated!

**Comment by Panoplos** [comment]
OK, I've modified the debug code to use `req.params.all()` as follows:

```
  // DEBUG >>
  var log = req._sails.log;
  log.debug(
    util.format('/%s/update called with req.query[%s]\n', req.options.model, JSON.stringify(req.query)) +
    util.format('                                  req.params[%s]',  JSON.stringify(req.params.all()))
  );
  // <<
```
and now I get the following:

```
debug: /user/update called with req.query[{}]
                                req.params[{"username":"foo","firstName":"bar","lastName":"baz","id":"54dd9b22ffe2e5211c1ca77d"}]
```

So, the values are getting passed in, however, the model is still not being updated!!

**Comment by Panoplos** [comment]
Upon further inspection, it looks like `actionUtil.parseValues( req, Model )` is returning an empty `object`.

I used the following debug code:

```
  // Create `values` object (monolithic combination of all parameters)
  // But omit the blacklisted params (like JSONP callback param, etc.)
  var values = actionUtil.parseValues( req, Model );

  // DEBUG >>
  log.debug(
    util.format('/%s/update: values[%s]', req.options.model, JSON.stringify(values))
  );
  // <<
```

Which outputs:

```
debug: /user/update: values[{}]
```

The `Model` object is being successfully retrieved from `actionUtil.parseModel( req )`, and the Primary Key is also successfully parsed...

Note that I am using MongoDB as DB server with sails-mongo. Before using `sails-ember-blueprints`, I was able to successfully manipulate the model via this method.

**Comment by Panoplos** [comment]
OK, figured out the issue. Looks like POST values need to be JSON formatted (as Ember.js formats its POSTs)! I assumed that the ember blueprint could handle all modes. My bad!!

**Comment by mphasize** [comment]
I guess we should make that clearer in the documentation, that the blueprints really only support Ember's style at the moment. Great that you could figure it out!

**Comment by Globegitter** [comment]
@Panoplos This has now also been added to the readme: https://github.com/mphasize/sails-generate-ember-blueprints#accessing-the-rest-interface-without-ember-data
